### ISSUE TITLE
Status of development?

### ISSUE THREAD

**Issue by bhrutledge** [novafloss/django-mail-factory#57]
My company is about to start using this library, and I'm curious if there's likely to be any further development and/or releases in the near future. Basically, we're wondering if it's in our best interest to pin ourselves to PyPI releases (and work around issues) or fork, fix, and PR as needed.

**Comment by rodo** [comment]
hi Brian,
Yes this project is still in production, we use it in our projects, and will welcome any PR you'll do to improve features or fix any bugs.
Regards
