### ISSUE TITLE
render() must be called with a dict, not a Context.

### ISSUE THREAD

**Issue by hsmett** [novafloss/django-mail-factory#71]
Hello!

We're currently upgrading to django 1.9 & then 1.10.
django-mail-factory is said to be django 1.10 ready, but I still get a deprecation warning:

/site-packages/mail_factory/mails.py:96: RemovedInDjango110Warning: render() must be called with a dict, not a Context. 
It seems you're still using the Context class, to render the templates, which is no more supported in django 1.10 and "works by accident". 
Ref:
https://github.com/django/django/blob/stable/1.9.x/django/template/backends/django.py#L65

Since you dropped the Dj1.7 support I guess you could just get rid of the Context class =)

Let me know if I can help, thank you for your hard work!

**Comment by vrialland** [comment]
👍 I was about to create the same ticket as the warning began to appear since our project upgrade to 1.9

**Comment by BojanKogoj** [comment]
Any chance this can be released soon? I'm running django 1.11.3 and it throws an exception, so I have to use the latest commit to make it work.

**Comment by wo0dyn** [comment]
@BojanKogoj: Release `0.18` on its way :wink: We were waiting a couple of weeks in case of anything else should be added to this release.
